/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.christianj98.online_store.schema;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class OrderKafkaRecord extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -7568120744524972336L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"OrderKafkaRecord\",\"namespace\":\"com.christianj98.online_store.schema\",\"fields\":[{\"name\":\"id\",\"type\":\"int\",\"doc\":\"id of the order\"},{\"name\":\"product\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"},\"doc\":\"product name\"},{\"name\":\"quantity\",\"type\":\"int\",\"doc\":\"quantity of the product\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<OrderKafkaRecord> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<OrderKafkaRecord> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<OrderKafkaRecord> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<OrderKafkaRecord> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<OrderKafkaRecord> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this OrderKafkaRecord to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a OrderKafkaRecord from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a OrderKafkaRecord instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static OrderKafkaRecord fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  /** id of the order */
  private int id;
  /** product name */
  private java.lang.String product;
  /** quantity of the product */
  private int quantity;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public OrderKafkaRecord() {}

  /**
   * All-args constructor.
   * @param id id of the order
   * @param product product name
   * @param quantity quantity of the product
   */
  public OrderKafkaRecord(java.lang.Integer id, java.lang.String product, java.lang.Integer quantity) {
    this.id = id;
    this.product = product;
    this.quantity = quantity;
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return id;
    case 1: return product;
    case 2: return quantity;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: id = (java.lang.Integer)value$; break;
    case 1: product = value$ != null ? value$.toString() : null; break;
    case 2: quantity = (java.lang.Integer)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'id' field.
   * @return id of the order
   */
  public int getId() {
    return id;
  }


  /**
   * Sets the value of the 'id' field.
   * id of the order
   * @param value the value to set.
   */
  public void setId(int value) {
    this.id = value;
  }

  /**
   * Gets the value of the 'product' field.
   * @return product name
   */
  public java.lang.String getProduct() {
    return product;
  }


  /**
   * Sets the value of the 'product' field.
   * product name
   * @param value the value to set.
   */
  public void setProduct(java.lang.String value) {
    this.product = value;
  }

  /**
   * Gets the value of the 'quantity' field.
   * @return quantity of the product
   */
  public int getQuantity() {
    return quantity;
  }


  /**
   * Sets the value of the 'quantity' field.
   * quantity of the product
   * @param value the value to set.
   */
  public void setQuantity(int value) {
    this.quantity = value;
  }

  /**
   * Creates a new OrderKafkaRecord RecordBuilder.
   * @return A new OrderKafkaRecord RecordBuilder
   */
  public static com.christianj98.online_store.schema.OrderKafkaRecord.Builder newBuilder() {
    return new com.christianj98.online_store.schema.OrderKafkaRecord.Builder();
  }

  /**
   * Creates a new OrderKafkaRecord RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new OrderKafkaRecord RecordBuilder
   */
  public static com.christianj98.online_store.schema.OrderKafkaRecord.Builder newBuilder(com.christianj98.online_store.schema.OrderKafkaRecord.Builder other) {
    if (other == null) {
      return new com.christianj98.online_store.schema.OrderKafkaRecord.Builder();
    } else {
      return new com.christianj98.online_store.schema.OrderKafkaRecord.Builder(other);
    }
  }

  /**
   * Creates a new OrderKafkaRecord RecordBuilder by copying an existing OrderKafkaRecord instance.
   * @param other The existing instance to copy.
   * @return A new OrderKafkaRecord RecordBuilder
   */
  public static com.christianj98.online_store.schema.OrderKafkaRecord.Builder newBuilder(com.christianj98.online_store.schema.OrderKafkaRecord other) {
    if (other == null) {
      return new com.christianj98.online_store.schema.OrderKafkaRecord.Builder();
    } else {
      return new com.christianj98.online_store.schema.OrderKafkaRecord.Builder(other);
    }
  }

  /**
   * RecordBuilder for OrderKafkaRecord instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<OrderKafkaRecord>
    implements org.apache.avro.data.RecordBuilder<OrderKafkaRecord> {

    /** id of the order */
    private int id;
    /** product name */
    private java.lang.String product;
    /** quantity of the product */
    private int quantity;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.christianj98.online_store.schema.OrderKafkaRecord.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.product)) {
        this.product = data().deepCopy(fields()[1].schema(), other.product);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.quantity)) {
        this.quantity = data().deepCopy(fields()[2].schema(), other.quantity);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
    }

    /**
     * Creates a Builder by copying an existing OrderKafkaRecord instance
     * @param other The existing instance to copy.
     */
    private Builder(com.christianj98.online_store.schema.OrderKafkaRecord other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.product)) {
        this.product = data().deepCopy(fields()[1].schema(), other.product);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.quantity)) {
        this.quantity = data().deepCopy(fields()[2].schema(), other.quantity);
        fieldSetFlags()[2] = true;
      }
    }

    /**
      * Gets the value of the 'id' field.
      * id of the order
      * @return The value.
      */
    public int getId() {
      return id;
    }


    /**
      * Sets the value of the 'id' field.
      * id of the order
      * @param value The value of 'id'.
      * @return This builder.
      */
    public com.christianj98.online_store.schema.OrderKafkaRecord.Builder setId(int value) {
      validate(fields()[0], value);
      this.id = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'id' field has been set.
      * id of the order
      * @return True if the 'id' field has been set, false otherwise.
      */
    public boolean hasId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'id' field.
      * id of the order
      * @return This builder.
      */
    public com.christianj98.online_store.schema.OrderKafkaRecord.Builder clearId() {
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'product' field.
      * product name
      * @return The value.
      */
    public java.lang.String getProduct() {
      return product;
    }


    /**
      * Sets the value of the 'product' field.
      * product name
      * @param value The value of 'product'.
      * @return This builder.
      */
    public com.christianj98.online_store.schema.OrderKafkaRecord.Builder setProduct(java.lang.String value) {
      validate(fields()[1], value);
      this.product = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'product' field has been set.
      * product name
      * @return True if the 'product' field has been set, false otherwise.
      */
    public boolean hasProduct() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'product' field.
      * product name
      * @return This builder.
      */
    public com.christianj98.online_store.schema.OrderKafkaRecord.Builder clearProduct() {
      product = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'quantity' field.
      * quantity of the product
      * @return The value.
      */
    public int getQuantity() {
      return quantity;
    }


    /**
      * Sets the value of the 'quantity' field.
      * quantity of the product
      * @param value The value of 'quantity'.
      * @return This builder.
      */
    public com.christianj98.online_store.schema.OrderKafkaRecord.Builder setQuantity(int value) {
      validate(fields()[2], value);
      this.quantity = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'quantity' field has been set.
      * quantity of the product
      * @return True if the 'quantity' field has been set, false otherwise.
      */
    public boolean hasQuantity() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'quantity' field.
      * quantity of the product
      * @return This builder.
      */
    public com.christianj98.online_store.schema.OrderKafkaRecord.Builder clearQuantity() {
      fieldSetFlags()[2] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public OrderKafkaRecord build() {
      try {
        OrderKafkaRecord record = new OrderKafkaRecord();
        record.id = fieldSetFlags()[0] ? this.id : (java.lang.Integer) defaultValue(fields()[0]);
        record.product = fieldSetFlags()[1] ? this.product : (java.lang.String) defaultValue(fields()[1]);
        record.quantity = fieldSetFlags()[2] ? this.quantity : (java.lang.Integer) defaultValue(fields()[2]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<OrderKafkaRecord>
    WRITER$ = (org.apache.avro.io.DatumWriter<OrderKafkaRecord>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<OrderKafkaRecord>
    READER$ = (org.apache.avro.io.DatumReader<OrderKafkaRecord>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeInt(this.id);

    out.writeString(this.product);

    out.writeInt(this.quantity);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.id = in.readInt();

      this.product = in.readString();

      this.quantity = in.readInt();

    } else {
      for (int i = 0; i < 3; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.id = in.readInt();
          break;

        case 1:
          this.product = in.readString();
          break;

        case 2:
          this.quantity = in.readInt();
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










